<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260602113757 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE build_version (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, version_id INT NOT NULL, build_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_9289AE4F4BBC2705 ON build_version (version_id)');
        $this->addSql('CREATE INDEX IDX_9289AE4F17C13F8B ON build_version (build_id)');
        $this->addSql('ALTER TABLE build_version ADD CONSTRAINT FK_9289AE4F4BBC2705 FOREIGN KEY (version_id) REFERENCES mcversion (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE build_version ADD CONSTRAINT FK_9289AE4F17C13F8B FOREIGN KEY (build_id) REFERENCES build (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE build_version DROP CONSTRAINT FK_9289AE4F4BBC2705');
        $this->addSql('ALTER TABLE build_version DROP CONSTRAINT FK_9289AE4F17C13F8B');
        $this->addSql('DROP TABLE build_version');
    }
}
