<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260521133305 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE comment_like (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, user_id_id INT NOT NULL, comment_id_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_8A55E25F9D86650F ON comment_like (user_id_id)');
        $this->addSql('CREATE INDEX IDX_8A55E25FD6DE06A6 ON comment_like (comment_id_id)');
        $this->addSql('ALTER TABLE comment_like ADD CONSTRAINT FK_8A55E25F9D86650F FOREIGN KEY (user_id_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE comment_like ADD CONSTRAINT FK_8A55E25FD6DE06A6 FOREIGN KEY (comment_id_id) REFERENCES comment (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE comment_like DROP CONSTRAINT FK_8A55E25F9D86650F');
        $this->addSql('ALTER TABLE comment_like DROP CONSTRAINT FK_8A55E25FD6DE06A6');
        $this->addSql('DROP TABLE comment_like');
    }
}
