<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260630120827 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE build_view (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, ip_hash VARCHAR(255) DEFAULT NULL, viewed_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, build_id_id INT NOT NULL, user_id_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_F981C6643F9CE95C ON build_view (build_id_id)');
        $this->addSql('CREATE INDEX IDX_F981C6649D86650F ON build_view (user_id_id)');
        $this->addSql('ALTER TABLE build_view ADD CONSTRAINT FK_F981C6643F9CE95C FOREIGN KEY (build_id_id) REFERENCES build (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE build_view ADD CONSTRAINT FK_F981C6649D86650F FOREIGN KEY (user_id_id) REFERENCES "user" (id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE build_view DROP CONSTRAINT FK_F981C6643F9CE95C');
        $this->addSql('ALTER TABLE build_view DROP CONSTRAINT FK_F981C6649D86650F');
        $this->addSql('DROP TABLE build_view');
    }
}
