<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260522094341 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE build_download (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, build_id INT NOT NULL, user_id_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_9C39D80617C13F8B ON build_download (build_id)');
        $this->addSql('CREATE INDEX IDX_9C39D8069D86650F ON build_download (user_id_id)');
        $this->addSql('ALTER TABLE build_download ADD CONSTRAINT FK_9C39D80617C13F8B FOREIGN KEY (build_id) REFERENCES build (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE build_download ADD CONSTRAINT FK_9C39D8069D86650F FOREIGN KEY (user_id_id) REFERENCES "user" (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE build_download DROP CONSTRAINT FK_9C39D80617C13F8B');
        $this->addSql('ALTER TABLE build_download DROP CONSTRAINT FK_9C39D8069D86650F');
        $this->addSql('DROP TABLE build_download');
    }
}
